version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rbac_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: ${DB_NAME:-rbac_system}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local